In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
import os
os.getcwd()

'C:\\Users\\mrabh\\Documents\\Untitled Folder'

In [2]:
dataset=pd.read_csv("D:\Data Set ML\Data.csv")

In [4]:
dataset.head(2)

Unnamed: 0   age   ed  employ  address  income  debtinc   creddebt  \
0           0  41.0  3.0    17.0     12.0   176.0      9.3  11.359392   
1           1  27.0  1.0    10.0      6.0    31.0     17.3   1.362202   

    othdebt  default  
0  5.008608      1.0  
1  4.000798      0.0

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  700 non-null    int64  
 1   age         700 non-null    float64
 2   ed          700 non-null    float64
 3   employ      700 non-null    float64
 4   address     700 non-null    float64
 5   income      700 non-null    float64
 6   debtinc     700 non-null    float64
 7   creddebt    700 non-null    float64
 8   othdebt     700 non-null    float64
 9   default     700 non-null    float64
dtypes: float64(9), int64(1)
memory usage: 54.8 KB


#### Preprocessing Part 1- Handling missing Value
#### Preprocessing Part-2- Encoding Parts
1. Label Encoder - Char to Num
2. One Hot Encoding - Change Different Columns By Using binary
3. Dummy Variable - (N-1)
#### Preprocessing Part 3- Outlier
#### Preprocessing Part 4- Feature scaling
1. Normalization (No OUtlier Then We GO 0 to 1) 
2. Standardriation (when Outlier Is Here -3 to +3)
#### Preprocessing Part 5- Imbalance Dataset
1. Using SMOTE
2. Over Sampling Method

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  700 non-null    int64  
 1   age         700 non-null    float64
 2   ed          700 non-null    float64
 3   employ      700 non-null    float64
 4   address     700 non-null    float64
 5   income      700 non-null    float64
 6   debtinc     700 non-null    float64
 7   creddebt    700 non-null    float64
 8   othdebt     700 non-null    float64
 9   default     700 non-null    float64
dtypes: float64(9), int64(1)
memory usage: 54.8 KB


In [11]:
dataset.isnull().any()

Unnamed: 0    False
age           False
ed            False
employ        False
address       False
income        False
debtinc       False
creddebt      False
othdebt       False
default       False
dtype: bool

In [9]:
dataset.head(2)

Unnamed: 0   age   ed  employ  address  income  debtinc   creddebt  \
0           0  41.0  3.0    17.0     12.0   176.0      9.3  11.359392   
1           1  27.0  1.0    10.0      6.0    31.0     17.3   1.362202   

    othdebt  default  
0  5.008608      1.0  
1  4.000798      0.0

In [12]:
dataset = dataset.drop(["Unnamed: 0"],axis=1)

In [15]:
dataset.head(2)

age   ed  employ  address  income  debtinc   creddebt   othdebt  default
0  41.0  3.0    17.0     12.0   176.0      9.3  11.359392  5.008608      1.0
1  27.0  1.0    10.0      6.0    31.0     17.3   1.362202  4.000798      0.0

In [16]:
x=dataset.drop(["default"],axis=1)
y=dataset["default"]

In [17]:
x

age   ed  employ  address  income  debtinc   creddebt   othdebt
0    41.0  3.0    17.0     12.0   176.0      9.3  11.359392  5.008608
1    27.0  1.0    10.0      6.0    31.0     17.3   1.362202  4.000798
2    40.0  1.0    15.0     14.0    55.0      5.5   0.856075  2.168925
3    41.0  1.0    15.0     14.0   120.0      2.9   2.658720  0.821280
4    24.0  2.0     2.0      0.0    28.0     17.3   1.787436  3.056564
..    ...  ...     ...      ...     ...      ...        ...       ...
695  36.0  2.0     6.0     15.0    27.0      4.6   0.262062  0.979938
696  29.0  2.0     6.0      4.0    21.0     11.5   0.369495  2.045505
697  33.0  1.0    15.0      3.0    32.0      7.6   0.491264  1.940736
698  45.0  1.0    19.0     22.0    77.0      8.4   2.302608  4.165392
699  37.0  1.0    12.0     14.0    44.0     14.7   2.994684  3.473316

[700 rows x 8 columns]

In [18]:
y

0      1.0
1      0.0
2      0.0
3      0.0
4      1.0
      ... 
695    1.0
696    0.0
697    0.0
698    0.0
699    0.0
Name: default, Length: 700, dtype: float64

In [ ]:
#### Standardrisation

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_sc=sc.fit_transform(x)
x_sc

array([[ 0.76830405,  1.37691065,  1.29431297, ..., -0.14079763,
         4.6348313 ,  0.59369176],
       [-0.98352929, -0.77932527,  0.24220057, ...,  1.03181795,
        -0.09044394,  0.28691947],
       [ 0.6431731 , -0.77932527,  0.99370943, ..., -0.69779002,
        -0.3296701 , -0.27069346],
       ...,
       [-0.23274357, -0.77932527,  0.99370943, ..., -0.38997844,
        -0.5021018 , -0.34015304],
       [ 1.26882787, -0.77932527,  1.59491651, ..., -0.27271688,
         0.35404868,  0.33702105],
       [ 0.26778024, -0.77932527,  0.54280411, ...,  0.65071788,
         0.68116556,  0.1263566 ]])

In [22]:
x_sc=pd.DataFrame(x_sc)
x_sc.head(2)

0         1         2         3         4         5         6  \
0  0.768304  1.376911  1.294313  0.545664  3.544603 -0.140798  4.634831   
1 -0.983529 -0.779325  0.242201 -0.334101 -0.396908  1.031818 -0.090444   

          7  
0  0.593692  
1  0.286919

In [23]:
dataset["default"].value_counts()

0.0    517
1.0    183
Name: default, dtype: int64

In [ ]:
# The data Is Imbalanced, hence We have To Use Oversampling method

In [24]:
import imblearn

In [25]:
from imblearn.over_sampling import RandomOverSampler
over =RandomOverSampler()
x_over,y_over=over.fit_resample(x,y)

In [27]:
print(x_over.shape)
print(y_over.shape)

(1034, 8)
(1034,)


## Now ready To Build My Model--

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_over,y_over,test_size=0.25,random_state=101)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(775, 8)
(259, 8)
(775,)
(259,)


# Building Model

#### Bagging Classifier

In [29]:
from sklearn.ensemble import BaggingClassifier
bagging=BaggingClassifier()
bagging.fit(x_train,y_train)

BaggingClassifier()

In [30]:
# Model Prediction
y_pred_train=bagging.predict(x_train)
y_pred_test=bagging.predict(x_test)

In [32]:
## Model Evaluation
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [33]:
print(classification_report(y_train,y_pred_train))
print("####"*25)
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       403
         1.0       1.00      0.99      1.00       372

    accuracy                           1.00       775
   macro avg       1.00      1.00      1.00       775
weighted avg       1.00      1.00      1.00       775

####################################################################################################
              precision    recall  f1-score   support

         0.0       0.87      0.79      0.83       114
         1.0       0.85      0.90      0.87       145

    accuracy                           0.85       259
   macro avg       0.86      0.85      0.85       259
weighted avg       0.85      0.85      0.85       259



In [34]:
print(confusion_matrix(y_train,y_pred_train))
print("####"*25)
print(confusion_matrix(y_test,y_pred_test))

[[403   0]
 [  2 370]]
####################################################################################################
[[ 90  24]
 [ 14 131]]


In [35]:
print(accuracy_score(y_train,y_pred_train))
print("####"*25)
print(accuracy_score(y_test,y_pred_test))

0.9974193548387097
####################################################################################################
0.8532818532818532


In [ ]:
# Bagging Accuracy:
# Train -99%
# Test - 85%





In [38]:
# Random Forest algorithm
from sklearn.ensemble import RandomForestClassifier
rforest=RandomForestClassifier()
rforest.fit(x_train,y_train)

RandomForestClassifier()

In [39]:
# Model Prediction
y_pred_rf_train=rforest.predict(x_train)
y_pred_rf_test=rforest.predict(x_test)

In [40]:
# Model Evaluation
print(classification_report(y_train,y_pred_rf_train))
print("####"*25)
print(classification_report(y_test,y_pred_rf_test))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       403
         1.0       1.00      1.00      1.00       372

    accuracy                           1.00       775
   macro avg       1.00      1.00      1.00       775
weighted avg       1.00      1.00      1.00       775

####################################################################################################
              precision    recall  f1-score   support

         0.0       0.92      0.86      0.89       114
         1.0       0.89      0.94      0.92       145

    accuracy                           0.90       259
   macro avg       0.91      0.90      0.90       259
weighted avg       0.90      0.90      0.90       259



In [41]:
print(confusion_matrix(y_train,y_pred_rf_train))
print("####"*25)
print(confusion_matrix(y_test,y_pred_rf_test))

[[403   0]
 [  0 372]]
####################################################################################################
[[ 98  16]
 [  9 136]]


In [42]:
print(accuracy_score(y_train,y_pred_rf_train))
print("####"*25)
print(accuracy_score(y_test,y_pred_rf_test))

1.0
####################################################################################################
0.9034749034749034


In [ ]:
# Bagging Accuracy:
# Train -99%
# Test - 85%


# Random Forest Accuracy:
# Train-100%
# Test-90.34%

# Gradient Boosting Accuracy:
# Train-
# Test-

In [44]:
# Gradient Boosting Algorithm
from sklearn.ensemble import GradientBoostingClassifier
gdboost=GradientBoostingClassifier()
gdboost.fit(x_train,y_train)

GradientBoostingClassifier()

In [45]:
# Model Prediction
y_pred_gdboost_train=gdboost.predict(x_train)
y_pred_gdboost_test=gdboost.predict(x_test)

In [49]:
# Model evaluation
print(classification_report(y_train,y_pred_gdboost_train))
print("####"*25)
print(classification_report(y_test,y_pred_gdboost_test))

              precision    recall  f1-score   support

         0.0       0.96      0.94      0.95       403
         1.0       0.93      0.95      0.94       372

    accuracy                           0.95       775
   macro avg       0.95      0.95      0.95       775
weighted avg       0.95      0.95      0.95       775

####################################################################################################
              precision    recall  f1-score   support

         0.0       0.82      0.82      0.82       114
         1.0       0.86      0.86      0.86       145

    accuracy                           0.85       259
   macro avg       0.84      0.84      0.84       259
weighted avg       0.85      0.85      0.85       259



In [50]:
print(confusion_matrix(y_train,y_pred_gdboost_train))
print("####"*25)
print(confusion_matrix(y_test,y_pred_gdboost_test))

[[378  25]
 [ 17 355]]
####################################################################################################
[[ 94  20]
 [ 20 125]]


In [51]:
print(accuracy_score(y_train,y_pred_gdboost_train))
print("####"*25)
print(accuracy_score(y_test,y_pred_gdboost_test))

0.9458064516129032
####################################################################################################
0.8455598455598455


In [ ]:
# Bagging Accuracy:
# Train -99%
# Test - 85%


# Random Forest Accuracy: ********************
# Train-100%
# Test-90.34%

# Gradient Boosting Accuracy:
# Train-94.58%
# Test-84.55%

#

In [53]:
# Adaboost Algorith
from sklearn.ensemble import AdaBoostClassifier
ada= AdaBoostClassifier()
ada.fit(x_train,y_train)

AdaBoostClassifier()

In [54]:
# Model Prediction
y_pred_ada_train=ada.predict(x_train)
y_pred_ada_test=ada.predict(x_test)

In [57]:
# Model Evaluation
print(classification_report(y_train,y_pred_ada_train))
print("####"*25)
print(classification_report(y_test,y_pred_ada_test))

              precision    recall  f1-score   support

         0.0       0.88      0.85      0.86       403
         1.0       0.84      0.87      0.86       372

    accuracy                           0.86       775
   macro avg       0.86      0.86      0.86       775
weighted avg       0.86      0.86      0.86       775

####################################################################################################
              precision    recall  f1-score   support

         0.0       0.78      0.82      0.79       114
         1.0       0.85      0.81      0.83       145

    accuracy                           0.81       259
   macro avg       0.81      0.81      0.81       259
weighted avg       0.82      0.81      0.82       259



In [58]:
print(confusion_matrix(y_train,y_pred_ada_train))
print("####"*25)
print(confusion_matrix(y_test,y_pred_ada_test))

[[343  60]
 [ 48 324]]
####################################################################################################
[[ 93  21]
 [ 27 118]]


In [59]:
print(accuracy_score(y_train,y_pred_ada_train))
print("####"*25)
print(accuracy_score(y_test,y_pred_ada_test))

0.8606451612903225
####################################################################################################
0.8146718146718147


In [ ]:
# Bagging Accuracy:
# Train -99%
# Test - 85%


# Random Forest Accuracy: ********************
# Train-100%
# Test-90.34%

# Gradient Boosting Accuracy:
# Train-94.58%
# Test-84.55%

# Gradient AdaBoost Accuracy:
# Train-86.06%
# Test-81.46%

#

In [60]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [61]:
# Model Prediction
y_pred_xgb_train=xgb.predict(x_train)
y_pred_xgb_test=xgb.predict(x_test)

In [62]:
# Model Evaluation
print(classification_report(y_train,y_pred_xgb_train))
print("####"*25)
print(classification_report(y_test,y_pred_xgb_test))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       403
         1.0       1.00      1.00      1.00       372

    accuracy                           1.00       775
   macro avg       1.00      1.00      1.00       775
weighted avg       1.00      1.00      1.00       775

####################################################################################################
              precision    recall  f1-score   support

         0.0       0.92      0.85      0.89       114
         1.0       0.89      0.94      0.92       145

    accuracy                           0.90       259
   macro avg       0.91      0.90      0.90       259
weighted avg       0.90      0.90      0.90       259



In [63]:
print(confusion_matrix(y_train,y_pred_xgb_train))
print("####"*25)
print(confusion_matrix(y_test,y_pred_xgb_test))

[[403   0]
 [  0 372]]
####################################################################################################
[[ 97  17]
 [  8 137]]


In [64]:
print(accuracy_score(y_train,y_pred_xgb_train))
print("####"*25)
print(accuracy_score(y_test,y_pred_xgb_test))

1.0
####################################################################################################
0.9034749034749034


In [ ]:
# Bagging Accuracy:
# Train -99%
# Test - 85%


# Random Forest Accuracy: ********************
# Train-100%
# Test-90.34%

# Gradient Boosting Accuracy:
# Train-94.58%
# Test-84.55%

# Gradient AdaBoost Accuracy:
# Train-86.06%
# Test-81.46%

# XGB Algorithm:
# Train-100%
# Test-90%

#

In [65]:
# Decision Tree algorithm
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [66]:
# Model Prediction
y_pred_dt_train=dt.predict(x_train)
y_pred_dt_test=dt.predict(x_test)

In [67]:
# Model Evaluation
print(classification_report(y_train,y_pred_dt_train))
print("####"*25)
print(classification_report(y_test,y_pred_dt_test))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       403
         1.0       1.00      1.00      1.00       372

    accuracy                           1.00       775
   macro avg       1.00      1.00      1.00       775
weighted avg       1.00      1.00      1.00       775

####################################################################################################
              precision    recall  f1-score   support

         0.0       0.90      0.76      0.82       114
         1.0       0.83      0.93      0.88       145

    accuracy                           0.86       259
   macro avg       0.87      0.85      0.85       259
weighted avg       0.86      0.86      0.86       259



In [68]:
print(confusion_matrix(y_train,y_pred_dt_train))
print("####"*25)
print(confusion_matrix(y_test,y_pred_dt_test))

[[403   0]
 [  0 372]]
####################################################################################################
[[ 87  27]
 [ 10 135]]


In [69]:
print(accuracy_score(y_train,y_pred_dt_train))
print("####"*25)
print(accuracy_score(y_test,y_pred_dt_test))

1.0
####################################################################################################
0.8571428571428571


In [ ]:
# Bagging Accuracy:
# Train -99%
# Test - 85%


# Random Forest Accuracy: ********************
# Train-100%
# Test-90.34%

# Gradient Boosting Accuracy:
# Train-94.58%
# Test-84.55%

# Gradient AdaBoost Accuracy:
# Train-86.06%
# Test-81.46%

# XGB Algorithm:
# Train-100%
# Test-90%

# Decision Tree Algorithm:
# Train-100%
# Test-85.71%

#

In [71]:
# Logistic Regression Algorithm
from sklearn.linear_model import LogisticRegression
logit=LogisticRegression()
logit.fit(x_train,y_train)

LogisticRegression()

In [72]:
# Model Prediction
y_pred_logit_train=logit.predict(x_train)
y_pred_logit_test=logit.predict(x_test)

In [73]:
# Model Evaluation
print(classification_report(y_train,y_pred_logit_train))
print("####"*25)
print(classification_report(y_test,y_pred_logit_test))

              precision    recall  f1-score   support

         0.0       0.80      0.77      0.79       403
         1.0       0.76      0.79      0.78       372

    accuracy                           0.78       775
   macro avg       0.78      0.78      0.78       775
weighted avg       0.78      0.78      0.78       775

####################################################################################################
              precision    recall  f1-score   support

         0.0       0.71      0.78      0.74       114
         1.0       0.81      0.74      0.78       145

    accuracy                           0.76       259
   macro avg       0.76      0.76      0.76       259
weighted avg       0.77      0.76      0.76       259



In [74]:
print(confusion_matrix(y_train,y_pred_logit_train))
print("####"*25)
print(confusion_matrix(y_test,y_pred_logit_test))

[[312  91]
 [ 77 295]]
####################################################################################################
[[ 89  25]
 [ 37 108]]


In [75]:
print(accuracy_score(y_train,y_pred_logit_train))
print("####"*25)
print(accuracy_score(y_test,y_pred_logit_test))

0.7832258064516129
####################################################################################################
0.7606177606177607


In [ ]:
# Bagging Accuracy:
# Train -99%
# Test - 85%


# Random Forest Accuracy: ********************
# Train-100%
# Test-90.34%

# Gradient Boosting Accuracy:
# Train-94.58%
# Test-84.55%

# Gradient AdaBoost Accuracy:
# Train-86.06%
# Test-81.46%

# XGBoost Algorithm:*******
# Train-100%
# Test-90%

# Decision Tree Accuracy:
# Train-100%
# Test-85.71%

# Logistic Regression logit Accuracy:
# Train-78.32%
# Test-76.06%